apiVersion: v1
kind: Service
metadata:
  name: ory-oathkeeper
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  oathkeeper_mapping
      prefix: /oathkeeper/
      service: ory-oathkeeper
      ---
      apiVersion: ambassador/v1
      kind:  AuthService
      name:  authentication
      auth_service: ory-oathkeeper
      path_prefix: /decisions
spec:
  ports:
    -
      name: http-ory-oathkeeper
      port: 80
      targetPort: http-api
  selector:
    app: ory-oathkeeper
  type: ClusterIP
