apiVersion: v1
kind: Service
metadata:
  name: ory-hydra
spec:
  ports:
    - name: http-ory-hydra-public
      port: 4444
      targetPort: public-api
    - name: http-ory-hydra-private
      port: 4445
      targetPort: private-api
  selector:
    app: ory-hydra
  type: ClusterIP
